Upgrade Google Guava to 30.1-jre
hawtio/hawtio pull request #2666
Opened 2020-12-18 08:06 UTC by jellisgwn

Fixes #2665

2020-12-18 08:11 UTC, oscerd requested changes
As I said in the issue, I'd be careful with this.

2020-12-18 08:15 UTC, jellisgwn commented
@oscerd thanks for the input. what are you requesting is changed?

2020-12-18 08:19 UTC, oscerd commented
Guava is known for introducing breaking changes and incompatibilities on each release. That's why I'm saying to be careful.

Also the CVE is a low impact one and we don't know if hawtio is really vulnerable or not. Static tool like Owasp Dependency Check are just reporting if a library is labelled or not with a CVE.. but there is no evidence about exploitability of the flaw.

2020-12-18 08:32 UTC, jellisgwn commented
Unfortunately "be careful" is not actionable. If specific areas of the code are heavily reliant of specific Guava behavior it would possible to validate that they have test coverage or can be manually tested.

For many organizations It is not realistic to ignore CVEs based on lack of direct evidence of an exploit. Hence my attempts to follow up on the reports update to non-vulnerable versions. OWASP Dependency Check is far from perfect, and that's why i'm also creating pull requests for false positives it reports against hawt.io

2020-12-18 08:35 UTC, oscerd commented
I understand that for many organizations is not realistic to ignore CVEs, but I still do believe that sometimes it would be useful to check the real impact of a vulnerability. Otherwise the value of static tool like OWASP dependency check will become useless.

2020-12-18 13:26 UTC, jellisgwn commented
https://github.com/google/guava

See point 2 in the section **Important Warnings**

> APIs without @Beta will remain binary-compatible for the indefinite future. (Previously, we sometimes removed such APIs after a deprecation period. The last release to remove non-@Beta APIs was Guava 21.0.) Even @Deprecated APIs will remain (again, unless they are @Beta). We have no plans to start removing things again, but officially, we're leaving our options open in case of surprises (like, say, a serious security problem).

Is the project using any @Beta tagged APIs? Otherwise the expectation should be that APIs are binary-compatible. I know that there have been issues in earlier Guava releases, but it looks like they have moved to address that.

2021-03-24 04:43 UTC, merged

2021-03-24 04:43 UTC, tadayosi commented
Thanks for your contribution!