Update connect page test
hawtio/hawtio pull request #3188
Opened 2024-01-25 13:22 UTC by kariuwu

2024-01-25 15:15 UTC, mmuzikar requested changes

2024-01-25 15:51 UTC, mmuzikar requested changes

2024-01-25 15:51 UTC, mmuzikar commented on tests/hawtio-test-suite/src/main/java/io/hawt/tests/features/pageobjects/pages/ConnectPage.java
> +        return;
We should eventually double check that the connection name already exists and not expect that there will always be just one connection, you can just add a todo and explanation of why this workaround exists.

2024-01-26 05:04 UTC, tadayosi approved these changes
Looks good to me other than what Martin pointed out.

2024-01-26 11:05 UTC, mmuzikar approved these changes

2024-01-26 11:53 UTC, merged